# Generated by Django 4.1.3 on 2023-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shopname', models.CharField(max_length=30)),
                ('Userid', models.CharField(max_length=30)),
                ('Itemid', models.CharField(max_length=30)),
                ('Product', models.CharField(max_length=30)),
                ('Image', models.CharField(max_length=30)),
                ('Catgry', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField(max_length=5)),
                ('Total', models.IntegerField(max_length=30)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
