# Generated by Django 4.1.3 on 2023-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=30)),
                ('Categry', models.CharField(max_length=30)),
                ('Subcat', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=10)),
                ('Info', models.CharField(max_length=200)),
                ('Stock', models.IntegerField(max_length=10)),
                ('Image', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Phonenum', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=30)),
                ('Longitude', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
