# Generated by Django 4.1.3 on 2023-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('splace', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('items', models.CharField(max_length=30)),
                ('categry', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=30)),
                ('datetime', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Auto_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Vehicleno', models.CharField(max_length=30)),
                ('Phonenum', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=30)),
                ('Longitude', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
