# Generated by Django 4.1.3 on 2023-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
